# Generated by Django 3.1.6 on 2021-06-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movi_name', models.CharField(max_length=20, null=True)),
                ('hero_name', models.CharField(max_length=30, null=True)),
                ('heroin_name', models.CharField(max_length=10, null=True)),
                ('rdate', models.CharField(max_length=15, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('star', models.CharField(max_length=20, null=True)),
                ('review', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
