# Generated by Django 3.1.6 on 2021-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='remail',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
