# Generated by Django 3.1.6 on 2021-06-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_movie_rid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=20, null=True)),
                ('review', models.CharField(max_length=30, null=True)),
                ('rname', models.CharField(max_length=30, null=True)),
                ('remail', models.CharField(max_length=30, null=True)),
                ('rid', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='remail',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rid',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rname',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star',
        ),
    ]
