# Generated by Django 3.1.6 on 2021-06-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20210623_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fake',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='mname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
